GET http://localhost:8080/main?num1=41115&num2=243&operation=sum

###
POST http://localhost:8080/reg?name=Andrei&login=Andrew&password=12345

###
POST http://localhost:8080/auth?login=Andrew&password=12345

###
POST http://localhost:8080/logout

###
POST http://localhost:8080/history?operation=sum

###
POST http://localhost:8080/history?operation=multiply

###
POST http://localhost:8080/history?operation=clear

###
POST http://localhost:8080/history?operation=showAll

###